name: Coana Vulnerability Analysis

on:
  schedule:
    - cron: '0 3 * * *' # every day at 3 AM
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manually run vulnerability analysis'
      # Required by the return-dispatch action
      distinct_id:

jobs:
  coana-vulnerability-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Coana CLI
        id: coana-cli
        uses: docker://coana/coana:latest@sha256:bd11eb205a4c48097d61819cb6f3e628a5b866ee76cbe1f1fe21f2f527ec7aa8
        with:
          args: |
            coana run . \
              --api-key ${{ secrets.COANA_API_KEY }} \
              --repo-url https://github.com/${{github.repository}}
