name: Coana Guardrail

on: pull_request

jobs:
  guardrail:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ' '
      - name: Checkout the ${{github.base_ref}} branch
        uses: actions/checkout@v4
        with:
          ## checkout the base branch (usually master/main).
          ref: ${{github.base_ref}}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Run Coana on the ${{github.base_ref}} branch
        run: |
          npx @coana-tech/cli run . \
            --api-key ${{ secrets.COANA_API_KEY }} \
            -o /tmp/main-branch \
            --changed-files \
            ${{ steps.changed-files.outputs.all_changed_files }} \
            --lightweight-reachability \
            --disable-report-submission \
            --repo-url https://github.com/${{github.repository}}
      - name: Checkout the current branch
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Run Coana on the current branch
        run: |
          npx @coana-tech/cli run . \
            --api-key ${{ secrets.COANA_API_KEY }} \
            -o /tmp/current-branch \
            --changed-files \
            ${{ steps.changed-files.outputs.all_changed_files }} \
            --lightweight-reachability \
            --disable-report-submission \
            --repo-url https://github.com/${{github.repository}}
      - name: Run Report Comparison
        run: |
          npx @coana-tech/cli compare-reports \
            --api-key ${{ secrets.COANA_API_KEY }} \
            --no-block \
            /tmp/main-branch/coana-report.json \
            /tmp/current-branch/coana-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
